/**
 * get_policy_details
 * Fetches up-to-date documentation for a specific policy from the Terraform registry. You must call 'search_policies' first to obtain the exact terraform_policy_id required to use this tool.
 * Auto-generated by mcp-to-claude-skill
 */

export interface GetPolicyDetailsInput {
  /**
   * Matching terraform_policy_id retrieved from the 'search_policies' tool (e.g., 'policies/hashicorp/CIS-Policy-Set-for-AWS-Terraform/1.0.1')
   */
  terraform_policy_id: string;
  [k: string]: unknown;
}

export interface GetPolicyDetailsOutput {
  content?: Array<{
    type: string;
    text?: string;
    [key: string]: any;
  }>;
  isError?: boolean;
  [key: string]: any;
}

/**
 * Fetches up-to-date documentation for a specific policy from the Terraform registry. You must call 'search_policies' first to obtain the exact terraform_policy_id required to use this tool.
 */
export async function GetPolicyDetails(
  input: GetPolicyDetailsInput
): Promise<GetPolicyDetailsOutput> {
  // This is a placeholder implementation
  // In a real implementation, this would call the MCP server
  throw new Error("MCP tool wrapper not yet implemented. Use MCP server directly.");
}
