/**
 * Organization - Organization and project listing
 * Auto-generated TypeScript interfaces from MCP server
 * Generated by mcp-to-claude-skill
 */

// Interface for tool: list_terraform_orgs
// Fetches a list of all Terraform organizations.
export interface ListTerraformOrgsInput {
  /**
   * Page number for pagination (min 1)
   */
  page?: number;
  /**
   * Results per page for pagination (min 1, max 100)
   */
  pageSize?: number;
  [k: string]: unknown;
}

// Interface for tool: list_terraform_projects
// Fetches a list of all Terraform projects.
export interface ListTerraformProjectsInput {
  /**
   * Page number for pagination (min 1)
   */
  page?: number;
  /**
   * Results per page for pagination (min 1, max 100)
   */
  pageSize?: number;
  /**
   * The name of the Terraform organization to list projects for.
   */
  terraform_org_name: string;
  [k: string]: unknown;
}
