/**
 * Tags - Workspace tagging operations
 * Auto-generated TypeScript interfaces from MCP server
 * Generated by mcp-to-claude-skill
 */

// Interface for tool: create_workspace_tags
// Add tags to a Terraform workspace.
export interface CreateWorkspaceTagsInput {
  /**
   * Comma-separated list of tag names to add, for key-value tags use key:value
   */
  tags: string;
  /**
   * Organization name
   */
  terraform_org_name: string;
  /**
   * Workspace name
   */
  workspace_name: string;
  [k: string]: unknown;
}

// Interface for tool: list_workspaces
// Search and list Terraform workspaces within a specified organization. Returns all workspaces when no filters are applied, or filters results based on name patterns, tags, or search queries. Supports pagination for large result sets.
export interface ListWorkspacesInput {
  /**
   * Optional comma-separated list of tags to exclude from results
   */
  exclude_tags?: string;
  /**
   * Page number for pagination (min 1)
   */
  page?: number;
  /**
   * Results per page for pagination (min 1, max 100)
   */
  pageSize?: number;
  /**
   * Optional project ID to filter workspaces
   */
  project_id?: string;
  /**
   * Optional search query to filter workspaces by name
   */
  search_query?: string;
  /**
   * Optional comma-separated list of tags to filter workspaces
   */
  tags?: string;
  /**
   * The Terraform organization name
   */
  terraform_org_name: string;
  /**
   * Optional wildcard pattern to match workspace names
   */
  wildcard_name?: string;
  [k: string]: unknown;
}

// Interface for tool: read_workspace_tags
// Read all tags from a Terraform workspace.
export interface ReadWorkspaceTagsInput {
  /**
   * Organization name
   */
  terraform_org_name: string;
  /**
   * Workspace name
   */
  workspace_name: string;
  [k: string]: unknown;
}
