/**
 * search_private_providers
 * This tool searches for private providers in your Terraform Cloud/Enterprise organization.
It retrieves a list of private providers that match the search criteria. This tool requires a valid Terraform token to be configured.
 * Auto-generated by mcp-to-claude-skill
 */

export interface SearchPrivateProvidersInput {
  /**
   * Page number for pagination (starts at 1)
   */
  page_number?: number;
  /**
   * Number of results to return per page (max 100)
   */
  page_size?: number;
  /**
   * The type of Terraform registry to search within Terraform Cloud/Enterprise (e.g., 'private', 'public')
   */
  registry_name?: "private" | "public";
  /**
   * Optional search query to filter providers by name or namespace. If not provided, all providers will be returned
   */
  search_query?: string;
  /**
   * The Terraform Cloud/Enterprise organization name to search within
   */
  terraform_org_name: string;
  [k: string]: unknown;
}

export interface SearchPrivateProvidersOutput {
  content?: Array<{
    type: string;
    text?: string;
    [key: string]: any;
  }>;
  isError?: boolean;
  [key: string]: any;
}

/**
 * This tool searches for private providers in your Terraform Cloud/Enterprise organization.
It retrieves a list of private providers that match the search criteria. This tool requires a valid Terraform token to be configured.
 */
export async function SearchPrivateProviders(
  input: SearchPrivateProvidersInput
): Promise<SearchPrivateProvidersOutput> {
  // This is a placeholder implementation
  // In a real implementation, this would call the MCP server
  throw new Error("MCP tool wrapper not yet implemented. Use MCP server directly.");
}
