/**
 * Workspaces - Workspace creation, configuration, and management
 * Auto-generated TypeScript interfaces from MCP server
 * Generated by mcp-to-claude-skill
 */

// Interface for tool: create_run
// Creates a new Terraform run in the specified workspace.
export interface CreateRunInput {
  /**
   * Optional message for the run
   */
  message?: string;
  /**
   * A run type for the run
   */
  run_type?: "plan_and_apply" | "refresh_state" | "plan_only" | "allow_empty_apply";
  /**
   * The Terraform Cloud/Enterprise organization name
   */
  terraform_org_name: string;
  /**
   * The name of the workspace to create a run in
   */
  workspace_name: string;
  [k: string]: unknown;
}

// Interface for tool: create_workspace
// Creates a new Terraform workspace in the specified organization. This is a destructive operation that will create new infrastructure resources.
export interface CreateWorkspaceInput {
  /**
   * Whether to automatically apply successful plans: 'true' or 'false' (default: 'false')
   */
  auto_apply?: string;
  /**
   * Optional description for the workspace
   */
  description?: string;
  /**
   * Execution mode: 'remote', 'local', or 'agent' (default: 'remote')
   */
  execution_mode?: string;
  /**
   * Optional project ID to associate the workspace with
   */
  project_id?: string;
  /**
   * Optional comma-separated list of tags to apply to the workspace
   */
  tags?: string;
  /**
   * The Terraform Cloud/Enterprise organization name
   */
  terraform_org_name: string;
  /**
   * Optional Terraform version to use (e.g., '1.5.0')
   */
  terraform_version?: string;
  /**
   * Optional VCS repository branch (default: main/master)
   */
  vcs_repo_branch?: string;
  /**
   * Optional VCS repository identifier (e.g., 'org/repo')
   */
  vcs_repo_identifier?: string;
  /**
   * OAuth token ID for VCS integration
   */
  vcs_repo_oauth_token_id?: string;
  /**
   * Optional working directory for Terraform operations
   */
  working_directory?: string;
  /**
   * The name of the workspace to create
   */
  workspace_name: string;
  [k: string]: unknown;
}

// Interface for tool: list_runs
// List or search Terraform runs in a specific workspace with optional filtering.
export interface ListRunsInput {
  /**
   * Page number for pagination (min 1)
   */
  page?: number;
  /**
   * Results per page for pagination (min 1, max 100)
   */
  pageSize?: number;
  /**
   * Optional run status filter
   */
  status?: (
    | "pending"
    | "fetching"
    | "fetching_completed"
    | "pre_plan_running"
    | "pre_plan_completed"
    | "queuing"
    | "plan_queued"
    | "planning"
    | "planned"
    | "cost_estimating"
    | "cost_estimated"
    | "policy_checking"
    | "policy_override"
    | "policy_soft_failed"
    | "policy_checked"
    | "confirmed"
    | "post_plan_running"
    | "post_plan_completed"
    | "planned_and_finished"
    | "planned_and_saved"
    | "apply_queued"
    | "applying"
    | "applied"
    | "discarded"
    | "errored"
    | "canceled"
    | "force_canceled"
  )[];
  /**
   * Lists the runs in Terraform Cloud/Enterprise organization based on filters if no workspace is specified
   */
  terraform_org_name: string;
  /**
   * Searches for runs that match the VCS username you supply
   */
  vcs_username?: string;
  /**
   * If specified, lists the runs in the given workspace instead of the organization based on filters
   */
  workspace_name?: string;
  [k: string]: unknown;
}

// Interface for tool: update_workspace
// Updates an existing Terraform workspace configuration. This is a potentially destructive operation that may affect infrastructure resources.
export interface UpdateWorkspaceInput {
  /**
   * Whether to automatically apply successful plans: 'true' or 'false'
   */
  auto_apply?: string;
  /**
   * Optional new description for the workspace
   */
  description?: string;
  /**
   * Execution mode: 'remote', 'local', or 'agent'
   */
  execution_mode?: string;
  /**
   * Whether file triggers are enabled: 'true' or 'false'
   */
  file_triggers_enabled?: string;
  /**
   * Optional new name for the workspace
   */
  new_name?: string;
  /**
   * Whether to queue all runs: 'true' or 'false'
   */
  queue_all_runs?: string;
  /**
   * Whether speculative plans are enabled: 'true' or 'false'
   */
  speculative_enabled?: string;
  /**
   * Optional comma-separated list of tags to replace existing tags
   */
  tags?: string;
  /**
   * The Terraform Cloud/Enterprise organization name
   */
  terraform_org_name: string;
  /**
   * Optional new Terraform version to use (e.g., '1.5.0')
   */
  terraform_version?: string;
  /**
   * Optional comma-separated list of trigger prefixes
   */
  trigger_prefixes?: string;
  /**
   * Optional new working directory for Terraform operations
   */
  working_directory?: string;
  /**
   * The name of the workspace to update
   */
  workspace_name: string;
  [k: string]: unknown;
}
