/**
 * Private Registry - Tools for accessing private Terraform modules and providers
 * Auto-generated TypeScript interfaces from MCP server
 * Generated by mcp-to-claude-skill
 */

// Interface for tool: get_private_module_details
// This tool retrieves detailed information about a specific private module in your Terraform Cloud/Enterprise organization.
It provides comprehensive details including inputs, outputs, dependencies, versions, and usage examples. The private_module_id format is 'module-namespace/module-name/module-provider-name'.
This can be obtained by calling 'search_private_modules' first to obtain the exact private_module_id required to use this tool. This tool requires a valid Terraform token to be configured.
export interface GetPrivateModuleDetailsInput {
  /**
   * The private module ID should be in the format 'module-namespace/module-name/module-provider-name' (for example, 'my-tfc-org/vpc/aws' or 'my-module-namespace/vm/azurerm').
   * The module-namespace is usually the name of the Terraform organization. Obtain this ID by calling 'search_private_modules'.
   */
  private_module_id: string;
  /**
   * Specific version of the module to retrieve details for. If not provided, the latest version will be used
   */
  private_module_version?: string;
  /**
   * The type of Terraform registry to search within Terraform Cloud/Enterprise (e.g., 'private', 'public')
   */
  registry_name?: "private" | "public";
  /**
   * The Terraform Cloud/Enterprise organization name
   */
  terraform_org_name: string;
  [k: string]: unknown;
}

// Interface for tool: get_private_provider_details
// This tool retrieves information about a specific private provider in your Terraform Cloud/Enterprise organization.
It provides details on how to use the provider, permissions, available versions, and more. This tool requires a valid Terraform token to be configured.

export interface GetPrivateProviderDetailsInput {
  /**
   * Whether to include detailed version information
   */
  include_versions?: boolean;
  /**
   * The name of the private provider
   */
  private_provider_name: string;
  /**
   * The namespace of the private provider in your Terraform Cloud/Enterprise organization. For public registry, use the namespace from the public Terraform registry.
   */
  private_provider_namespace: string;
  /**
   * The type of Terraform registry to search within Terraform Cloud/Enterprise (e.g., 'private', 'public')
   */
  registry_name?: "private" | "public";
  /**
   * The Terraform Cloud/Enterprise organization name
   */
  terraform_org_name: string;
  [k: string]: unknown;
}

// Interface for tool: search_private_modules
// This tool searches for private modules in your Terraform Cloud/Enterprise organization.
It retrieves a list of private modules that match the search criteria. This tool requires a valid Terraform token to be configured.
export interface SearchPrivateModulesInput {
  /**
   * Page number for pagination (starts at 1)
   */
  page_number?: number;
  /**
   * Number of results to return per page (max 100)
   */
  page_size?: number;
  /**
   * Optional search query to filter modules by name or namespace. If not provided, all modules will be returned
   */
  search_query?: string;
  /**
   * The Terraform Cloud/Enterprise organization name to search within
   */
  terraform_org_name: string;
  [k: string]: unknown;
}

// Interface for tool: search_private_providers
// This tool searches for private providers in your Terraform Cloud/Enterprise organization.
It retrieves a list of private providers that match the search criteria. This tool requires a valid Terraform token to be configured.
export interface SearchPrivateProvidersInput {
  /**
   * Page number for pagination (starts at 1)
   */
  page_number?: number;
  /**
   * Number of results to return per page (max 100)
   */
  page_size?: number;
  /**
   * The type of Terraform registry to search within Terraform Cloud/Enterprise (e.g., 'private', 'public')
   */
  registry_name?: "private" | "public";
  /**
   * Optional search query to filter providers by name or namespace. If not provided, all providers will be returned
   */
  search_query?: string;
  /**
   * The Terraform Cloud/Enterprise organization name to search within
   */
  terraform_org_name: string;
  [k: string]: unknown;
}
