/**
 * create_no_code_workspace
 * Creates a new Terraform No Code module workspace. The tool uses the MCP elicitation feature to automatically discover and collect required variables from the user.
 * Auto-generated by mcp-to-claude-skill
 */

export interface CreateNoCodeWorkspaceInput {
  /**
   * Whether to automatically apply changes in the workspace: 'true' or 'false'
   */
  auto_apply?: boolean;
  /**
   * The ID of the No Code module to create a workspace for
   */
  no_code_module_id: string;
  /**
   * The ID of the project to use
   */
  project_id: string;
  /**
   * The name of the workspace to create
   */
  workspace_name: string;
  [k: string]: unknown;
}

export interface CreateNoCodeWorkspaceOutput {
  content?: Array<{
    type: string;
    text?: string;
    [key: string]: any;
  }>;
  isError?: boolean;
  [key: string]: any;
}

/**
 * Creates a new Terraform No Code module workspace. The tool uses the MCP elicitation feature to automatically discover and collect required variables from the user.
 */
export async function CreateNoCodeWorkspace(
  input: CreateNoCodeWorkspaceInput
): Promise<CreateNoCodeWorkspaceOutput> {
  // This is a placeholder implementation
  // In a real implementation, this would call the MCP server
  throw new Error("MCP tool wrapper not yet implemented. Use MCP server directly.");
}
