/**
 * create_workspace_variable
 * Create a new variable in a Terraform workspace.
 * Auto-generated by mcp-to-claude-skill
 */

export interface CreateWorkspaceVariableInput {
  /**
   * Variable category: terraform or env
   */
  category?: "terraform" | "env";
  /**
   * Variable description
   */
  description?: string;
  /**
   * Whether variable is HCL: true or false
   */
  hcl?: boolean;
  /**
   * Variable key/name
   */
  key: string;
  /**
   * Whether variable is sensitive: true or false
   */
  sensitive?: boolean;
  /**
   * Organization name
   */
  terraform_org_name: string;
  /**
   * Variable value
   */
  value: string;
  /**
   * Workspace name
   */
  workspace_name: string;
  [k: string]: unknown;
}

export interface CreateWorkspaceVariableOutput {
  content?: Array<{
    type: string;
    text?: string;
    [key: string]: any;
  }>;
  isError?: boolean;
  [key: string]: any;
}

/**
 * Create a new variable in a Terraform workspace.
 */
export async function CreateWorkspaceVariable(
  input: CreateWorkspaceVariableInput
): Promise<CreateWorkspaceVariableOutput> {
  // This is a placeholder implementation
  // In a real implementation, this would call the MCP server
  throw new Error("MCP tool wrapper not yet implemented. Use MCP server directly.");
}
