/**
 * delete_variable_in_variable_set
 * Delete a variable in a variable set.
 * Auto-generated by mcp-to-claude-skill
 */

export interface DeleteVariableInVariableSetInput {
  /**
   * Variable ID to delete
   */
  variable_id: string;
  /**
   * Variable set ID
   */
  variable_set_id: string;
  [k: string]: unknown;
}

export interface DeleteVariableInVariableSetOutput {
  content?: Array<{
    type: string;
    text?: string;
    [key: string]: any;
  }>;
  isError?: boolean;
  [key: string]: any;
}

/**
 * Delete a variable in a variable set.
 */
export async function DeleteVariableInVariableSet(
  input: DeleteVariableInVariableSetInput
): Promise<DeleteVariableInVariableSetOutput> {
  // This is a placeholder implementation
  // In a real implementation, this would call the MCP server
  throw new Error("MCP tool wrapper not yet implemented. Use MCP server directly.");
}
