/**
 * get_workspace_details
 * Fetches detailed information about a specific Terraform workspace, including configuration, variables, and current state information.
 * Auto-generated by mcp-to-claude-skill
 */

export interface GetWorkspaceDetailsInput {
  /**
   * The Terraform Cloud/Enterprise organization name
   */
  terraform_org_name: string;
  /**
   * The name of the workspace to get details for
   */
  workspace_name: string;
  [k: string]: unknown;
}

export interface GetWorkspaceDetailsOutput {
  content?: Array<{
    type: string;
    text?: string;
    [key: string]: any;
  }>;
  isError?: boolean;
  [key: string]: any;
}

/**
 * Fetches detailed information about a specific Terraform workspace, including configuration, variables, and current state information.
 */
export async function GetWorkspaceDetails(
  input: GetWorkspaceDetailsInput
): Promise<GetWorkspaceDetailsOutput> {
  // This is a placeholder implementation
  // In a real implementation, this would call the MCP server
  throw new Error("MCP tool wrapper not yet implemented. Use MCP server directly.");
}
