/**
 * list_variable_sets
 * List all variable sets in an organization. Returns all if query is empty.
 * Auto-generated by mcp-to-claude-skill
 */

export interface ListVariableSetsInput {
  /**
   * Page number for pagination (min 1)
   */
  page?: number;
  /**
   * Results per page for pagination (min 1, max 100)
   */
  pageSize?: number;
  /**
   * Optional filter query for variable set names
   */
  query?: string;
  /**
   * Organization name
   */
  terraform_org_name: string;
  [k: string]: unknown;
}

export interface ListVariableSetsOutput {
  content?: Array<{
    type: string;
    text?: string;
    [key: string]: any;
  }>;
  isError?: boolean;
  [key: string]: any;
}

/**
 * List all variable sets in an organization. Returns all if query is empty.
 */
export async function ListVariableSets(
  input: ListVariableSetsInput
): Promise<ListVariableSetsOutput> {
  // This is a placeholder implementation
  // In a real implementation, this would call the MCP server
  throw new Error("MCP tool wrapper not yet implemented. Use MCP server directly.");
}
