/**
 * Variables - Variable and variable set management
 * Auto-generated TypeScript interfaces from MCP server
 * Generated by mcp-to-claude-skill
 */

// Interface for tool: attach_variable_set_to_workspaces
// Attach a variable set to one or more workspaces.
export interface AttachVariableSetToWorkspacesInput {
  /**
   * Variable set ID
   */
  variable_set_id: string;
  /**
   * Comma-separated list of workspace IDs
   */
  workspace_ids: string;
  [k: string]: unknown;
}

// Interface for tool: create_no_code_workspace
// Creates a new Terraform No Code module workspace. The tool uses the MCP elicitation feature to automatically discover and collect required variables from the user.
export interface CreateNoCodeWorkspaceInput {
  /**
   * Whether to automatically apply changes in the workspace: 'true' or 'false'
   */
  auto_apply?: boolean;
  /**
   * The ID of the No Code module to create a workspace for
   */
  no_code_module_id: string;
  /**
   * The ID of the project to use
   */
  project_id: string;
  /**
   * The name of the workspace to create
   */
  workspace_name: string;
  [k: string]: unknown;
}

// Interface for tool: create_variable_in_variable_set
// Create a new variable in a variable set.
export interface CreateVariableInVariableSetInput {
  /**
   * Variable category: terraform or env
   */
  category?: "terraform" | "env";
  /**
   * Variable description
   */
  description?: string;
  /**
   * Whether variable is HCL: true or false
   */
  hcl?: boolean;
  /**
   * Variable key/name
   */
  key: string;
  /**
   * Whether variable is sensitive: true or false
   */
  sensitive?: boolean;
  /**
   * Variable value
   */
  value: string;
  /**
   * Variable set ID
   */
  variable_set_id: string;
  [k: string]: unknown;
}

// Interface for tool: create_variable_set
// Create a new variable set in an organization.
export interface CreateVariableSetInput {
  /**
   * Variable set description
   */
  description?: string;
  /**
   * Whether variable set is global: true or false
   */
  global?: boolean;
  /**
   * Variable set name
   */
  name: string;
  /**
   * Organization name
   */
  terraform_org_name: string;
  [k: string]: unknown;
}

// Interface for tool: create_workspace_variable
// Create a new variable in a Terraform workspace.
export interface CreateWorkspaceVariableInput {
  /**
   * Variable category: terraform or env
   */
  category?: "terraform" | "env";
  /**
   * Variable description
   */
  description?: string;
  /**
   * Whether variable is HCL: true or false
   */
  hcl?: boolean;
  /**
   * Variable key/name
   */
  key: string;
  /**
   * Whether variable is sensitive: true or false
   */
  sensitive?: boolean;
  /**
   * Organization name
   */
  terraform_org_name: string;
  /**
   * Variable value
   */
  value: string;
  /**
   * Workspace name
   */
  workspace_name: string;
  [k: string]: unknown;
}

// Interface for tool: delete_variable_in_variable_set
// Delete a variable in a variable set.
export interface DeleteVariableInVariableSetInput {
  /**
   * Variable ID to delete
   */
  variable_id: string;
  /**
   * Variable set ID
   */
  variable_set_id: string;
  [k: string]: unknown;
}

// Interface for tool: detach_variable_set_from_workspaces
// Detach a variable set from one or more workspaces.
export interface DetachVariableSetFromWorkspacesInput {
  /**
   * Variable set ID
   */
  variable_set_id: string;
  /**
   * Comma-separated list of workspace IDs
   */
  workspace_ids: string;
  [k: string]: unknown;
}

// Interface for tool: get_workspace_details
// Fetches detailed information about a specific Terraform workspace, including configuration, variables, and current state information.
export interface GetWorkspaceDetailsInput {
  /**
   * The Terraform Cloud/Enterprise organization name
   */
  terraform_org_name: string;
  /**
   * The name of the workspace to get details for
   */
  workspace_name: string;
  [k: string]: unknown;
}

// Interface for tool: list_variable_sets
// List all variable sets in an organization. Returns all if query is empty.
export interface ListVariableSetsInput {
  /**
   * Page number for pagination (min 1)
   */
  page?: number;
  /**
   * Results per page for pagination (min 1, max 100)
   */
  pageSize?: number;
  /**
   * Optional filter query for variable set names
   */
  query?: string;
  /**
   * Organization name
   */
  terraform_org_name: string;
  [k: string]: unknown;
}

// Interface for tool: list_workspace_variables
// List all variables in a Terraform workspace. Returns all variables if query is empty.
export interface ListWorkspaceVariablesInput {
  /**
   * Page number for pagination (min 1)
   */
  page?: number;
  /**
   * Results per page for pagination (min 1, max 100)
   */
  pageSize?: number;
  /**
   * Organization name
   */
  terraform_org_name: string;
  /**
   * Workspace name
   */
  workspace_name: string;
  [k: string]: unknown;
}

// Interface for tool: update_workspace_variable
// Update an existing variable in a Terraform workspace.
export interface UpdateWorkspaceVariableInput {
  /**
   * Variable description
   */
  description?: string;
  /**
   * Whether variable is HCL: true or false
   */
  hcl?: boolean;
  /**
   * Variable key/name
   */
  key: string;
  /**
   * Whether variable is sensitive: true or false
   */
  sensitive?: boolean;
  /**
   * Organization name
   */
  terraform_org_name: string;
  /**
   * Variable value
   */
  value: string;
  /**
   * Variable ID to update
   */
  variable_id: string;
  /**
   * Workspace name
   */
  workspace_name: string;
  [k: string]: unknown;
}
