/**
 * Other - Additional tools
 * Auto-generated TypeScript interfaces from MCP server
 * Generated by mcp-to-claude-skill
 */

// Interface for tool: get_latest_module_version
// Fetches the latest version of a Terraform module from the public registry
export interface GetLatestModuleVersionInput {
  /**
   * The name of the module, this is usually the service or group of service the user is deploying e.g., 'security-group', 'secrets-manager' etc.
   */
  module_name: string;
  /**
   * The name of the Terraform provider for the module, e.g., 'aws', 'google', 'azurerm' etc.
   */
  module_provider: string;
  /**
   * The publisher of the module, e.g., 'hashicorp', 'aws-ia', 'terraform-google-modules', 'Azure' etc.
   */
  module_publisher: string;
  [k: string]: unknown;
}

// Interface for tool: get_latest_provider_version
// Fetches the latest version of a Terraform provider from the public registry
export interface GetLatestProviderVersionInput {
  /**
   * The name of the Terraform provider, e.g., 'aws', 'azurerm', 'google', etc.
   */
  name: string;
  /**
   * The namespace of the Terraform provider, typically the name of the company, or their GitHub organization name that created the provider e.g., 'hashicorp'
   */
  namespace: string;
  [k: string]: unknown;
}
