/**
 * Runs - Terraform run creation and monitoring
 * Auto-generated TypeScript interfaces from MCP server
 * Generated by mcp-to-claude-skill
 */

// Interface for tool: get_run_details
// Fetches detailed information about a specific Terraform run.
export interface GetRunDetailsInput {
  /**
   * The ID of the run to get details for
   */
  run_id: string;
  [k: string]: unknown;
}
